iDeLog3DSetUp=DefineParametersiDeLog3D;

% 1) Start with an empty scalar struct
new_params = struct();

% 2) Copy the ParamiDeLog3D fields explicitly
Param_fields = { ...
    .... Spatial parameters
    'iDeLog_target_and_intermediate_x_points', ...
    'iDeLog_target_and_intermediate_y_points', ...
    'iDeLog_target_and_intermediate_z_points', ...
    'iDeLog_u_plane_vectors', ...
    'iDeLog_v_plane_vectors', ...
    'iDeLog_start_angles', ...
    'iDeLog_end_angles', ...
    ... Analytical parameters
    'iDeLog_parameters_bell_functions', ...
    'iDeLog_to_of_bell_functions', ...
    ... Fixed parameters
    'iDeLog_type_of_bell_shape_functions', ...
    'iDeLog_type_of_links', ...
    'fmonline', ...
    'resolution', ...
    ... Each '1' for each stroke
    'weight_splitted_bell_functions'};

for k = 1:numel(Param_fields)
    f = Param_fields{k};
    new_params.(f) = ParamiDeLog3D.(f);   % one-by-one, no cell-array expansion
end

% 3) Merge the setup fields
iDeLog3DSetUp = DefineParametersiDeLog3D;
setup_fields  = fieldnames(iDeLog3DSetUp);
for k = 1:numel(setup_fields)
    f = setup_fields{k};
    new_params.(f) = iDeLog3DSetUp.(f);
end

% 4) Run reconstruction
[xr,yr,pr,RecoiDeLog3D]=ReconstructiDeLog3D(new_params,ttotalfirma,DRAW,WRITE);
